### ISSUE TITLE
MailboxLogin is not enabled by default should it be? 

### ISSUE THREAD

**Issue by JBines** [o365soa/Scripts#12]
Hi Scott I see you have recently pulled the MailboxLogin from the script. Something change that I'm not aware of from our last discussion?

MailboxLogin is not enabled by default.  The check mark indicates that it can be enabled, but the lack of an asterisk means it is not enabled by default.

As for custom actions, yes, they will not be retained if any of the recommended actions are missing (but will be retained if no update is needed because at least the recommended actions are being logged).  I explored the option of retaining custom actions, but it will require more work to use something like a hash table to store the custom actions for a given mailbox and then [re]apply them after restoring the defaults.  This script is meant to be used as a way for customers to easily enable audit logging for the appropriate mailboxes and the recommended actions, but will not necessarily suit all customers, especially those who have custom actions.  (I originally did have code so you can add any custom actions that should be applied to all mailboxes, but it led to so many other what if this, what if that scenarios that I removed it.)

_Originally posted by @sbueffel in https://github.com/o365soa/Scripts/issues/6#issuecomment-680148896_

**Comment by sbueffel** [comment]
MailboxLogin is not enabled by the script anymore because it provides limited value.  This is because the action, when enabled, is not logged for clients using modern authentication or certificate-based authentication.  This can provide a false sense of security if you are not aware that not all login types are actually logged.  Modern auth clients have never been logged for this action, so it isn't a regression.  There has been an active design change request (DCR) for years for all login types to be logged, but it has yet to be implemented.

When the script was updated to remove MailboxLogin, it was also updated to preserve custom actions, storing them in a property of a custom object and then reapplied after resetting the baseline actions.

**Comment by JBines** [comment]
Cheers scott for the update. I see... I've updated my script to enable App Only auth to EXO in Azure Automation. We are running this eveyday for a few customers just to apply the setting for new mailboxes. I've included the mailboxlogin for now as it does not hurt to keep it... As always the hard part is understanding the data. :)   https://github.com/JBines/Enable-MailboxAuditing.ps1
