### ISSUE TITLE
[Feature Request] `Get-InactiveUsers.ps1` and Best Practices

### ISSUE THREAD

**Issue by ghost** [o365soa/Scripts#31]
Hello,

Thank you for the scripts provided. However, I did notice that `Get-InactiveUsers.ps1` is not necessarily following best practices due to the usage of `+=` and `New-Object`

Using `+=` to add to an array is largely inefficient due to how Powershell handles adding to an array. It is recommended to use a [Generic List](https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-arrays?view=powershell-7.4#generic-list) instead.

```powershell
    $result += $response.Value
````

```powershell
            $return += New-Object -TypeName PSObject -Property @{
```

There's no need to use `New-Object` to initialize your PSCustomObject and this is considered a [legacy approach](https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-pscustomobject?view=powershell-7.4#legacy-approach).

```powershell
            $return += New-Object -TypeName PSObject -Property @{
```

https://github.com/o365soa/Scripts/blob/7085801e461568790aa0bda1da695a4757868c4c/Get-InactiveUsers.ps1#L94
https://github.com/o365soa/Scripts/blob/7085801e461568790aa0bda1da695a4757868c4c/Get-InactiveUsers.ps1#L105

I am happy to provide a PR but not sure if you guys are currently accepting PRs or not.

**Comment by sbueffel** [comment]
Yes, using += is not efficient with large collections (though this is improved in PS 7.5). It isn't as much of a concern here because the number of times something is being added to the array is the number of pages in the response. For most organizations, it won't be so many that the performance impact is noticeable. However, we will consider changing this the next time the script is updated. (The last successful sign-in is now available using the /v1.0 endpoint, for example, so it will likely be updated soon.)
