### ISSUE TITLE
Updates to Configure-MailboxAuditing.ps1

### ISSUE THREAD

**Issue by JBines** [o365soa/Scripts#6]
Thanks for updating this script. I'm trying to understand some of these changes.

1. Script states "The recommended actions are those enabled by default plus MailboxLogin" Going from the image this already appears to be included by default?  Maybe i'm missing something...
2. The script will return to default any custom auditing. Might need to add a note in the script or make the script additive only which would be posiable. 

@sbueffel 

![image](https://user-images.githubusercontent.com/40031426/90517981-7095ca00-e166-11ea-9062-badb0abcdeff.png)

**Comment by sbueffel** [comment]
MailboxLogin is not enabled by default.  The check mark indicates that it can be enabled, but the lack of an asterisk means it is not enabled by default.

As for custom actions, yes, they will not be retained if any of the recommended actions are missing (but will be retained if no update is needed because at least the recommended actions are being logged).  I explored the option of retaining custom actions, but it will require more work to use something like a hash table to store the custom actions for a given mailbox and then [re]apply them after restoring the defaults.  This script is meant to be used as a way for customers to easily enable audit logging for the appropriate mailboxes and the recommended actions, but will not necessarily suit all customers, especially those who have custom actions.  (I originally did have code so you can add any custom actions that should be applied to all mailboxes, but it led to so many other what if this, what if that scenarios that I removed it.)

**Comment by JBines** [comment]
Hey thanks for the reply. So turns out I was missing something :) will not be the first or the last but rest assured I will try to read the finer details next time! 

Totally get the whatif's and these small things turning into bigger than ben hur. I have been thinking about simply checking if mailboxes could have the default auditing enabled and if it has the extra audit mailboxlogin and just adding them. Now i'm thinking out aloud could you enable the default audit logging on a mailbox and then manually remove the default values. Maybe? if not that might simplify things and you will just need to remove resetting the -DefaultAuditSet 

B
J

**Comment by JBines** [comment]
Hi Scott I see you have recently pulled the MailboxLogin from the script. Something change that I'm not aware of from our last discussion?
